<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Adv Prod Types' => 'Виды рекламных изделий',
    'Are you sure you want to delete this item?' => 'Вы уверены, что нужно удалить запись?',
    'Calculation Has Materials' => 'Материалы в расчете',
    'Calculation ID' => 'Номер расчета',
    'Calculations' => 'Расчеты',
    'Colors' => 'Цвета',
    'Create Adv Prod Type' => 'Добавить вид рекламного изделия',
    'Create Calculation' => 'Добавить расчет',
    'Create Calculation Has Material' => 'Добавить материал',
    'Create Color' => 'Добавить цвет',
    'Create Customer' => 'Добавить клиента',
    'Create Employee' => 'Добавить сотрудника',
    'Create Material' => 'Добавить материал',
    'Create Order' => 'Добавить заказ',
    'Create Price List' => 'Заполнить прайс-лист',
    'Customers' => 'Клиенты',
    'Delete' => 'Удалить',
    'Employees' => 'Сотрудники',
    'Materials' => 'Материалы',
    'Orders' => 'Заказы',
    'Price Lists' => 'Прайс-лист',
    'Reset' => 'Отмена',
    'Save' => 'Сохранить',
    'Search' => 'Поиска',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует',
    'Update' => 'Обновить',
    'Adv Prod Type ID' => '',
    'Calculationcol' => '',
    'Color' => '',
    'Color ID' => '',
    'Cost' => '',
    'Customer ID' => '',
    'Description' => '',
    'Email' => '',
    'Employees ID' => '',
    'Fullname' => '',
    'ID' => '',
    'Item Name' => '',
    'Material Count' => '',
    'Material Height' => '',
    'Material ID' => '',
    'Material Length' => '',
    'Material Width' => '',
    'Materialcost' => '',
    'Materialtitle' => '',
    'Ordercol' => '',
    'Orderdate' => '',
    'Phonenumber' => '',
    'Product Height' => '',
    'Product Length' => '',
    'Product Quantity' => '',
    'Product Width' => '',
    'Title' => '',
    'Update Adv Prod Type: {name}' => '',
    'Update Calculation Has Material: {name}' => '',
    'Update Calculation: {name}' => '',
    'Update Color: {name}' => '',
    'Update Customer: {name}' => '',
    'Update Employee: {name}' => '',
    'Update Material: {name}' => '',
    'Update Order: {name}' => '',
    'Update Price List: {name}' => '',
    'User ID' => '',
];
