<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Adv Prod Types' => 'Виды изделий',
    'Are you sure you want to delete this item?' => 'Вы уверены, что нужно удалить запись?',
    'Calculation Has Materials' => 'Материалы в расчете',
    'Calculation ID' => 'Расчет',
    'Calculations' => 'Расчеты',
    'Colors' => 'Цвета',
    'Create Adv Prod Type' => 'Добавить вид рекламного изделия',
    'Create Calculation' => 'Добавить расчет',
    'Create Calculation Has Material' => 'Добавить материал',
    'Create Color' => 'Добавить цвет',
    'Create Customer' => 'Добавить клиента',
    'Create Employee' => 'Добавить сотрудника',
    'Create Material' => 'Добавить материал',
    'Create Order' => 'Добавить заказ',
    'Create Price List' => 'Заполнить прайс-лист',
    'Customers' => 'Клиенты',
    'Delete' => 'Удалить',
    'Employees' => 'Сотрудники',
    'Materials' => 'Материалы',
    'Orders' => 'Заказы',
    'Price Lists' => 'Прайс-лист',
    'Reset' => 'Отмена',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует',
    'Update' => 'Обновить',
    'Adv Prod Type ID' => 'Вид рекламного изделия',
    'Calculationcol' => 'Расчет',
    'Color' => 'Цвет',
    'Color ID' => 'Цвет',
    'Cost' => 'Стоимость',
    'Customer ID' => 'Клиент',
    'Description' => 'Описание',
    'Email' => 'Электронный адрес',
    'Employees ID' => 'Сотрудник',
    'Fullname' => 'ФИО',
    'ID' => 'Номер',
    'Item Name' => 'Наименование',
    'Material Count' => 'Количество материала',
    'Material Height' => 'Высота',
    'Material ID' => 'Материал',
    'Material Length' => 'Длина',
    'Material Width' => 'Ширина',
    'Materialcost' => 'Стоимость',
    'Materialtitle' => 'Наименование',
    'Ordercol' => 'Заказ',
    'Orderdate' => 'Дата заказа',
    'Phonenumber' => 'Номер телефона',
    'Calculation and Save' => 'Рассчитать и сохранить',
    'Product Height' => 'Высота',
    'Product Length' => 'Длина',
    'Product Quantity' => 'Количество',
    'Product Width' => 'Ширина',
    'Title' => 'Название',
    'Update Adv Prod Type: {name}' => 'Обновить вид изделия: {name}',
    'Update Calculation Has Material: {name}' => 'Обновить материалы в расчете: {name}',
    'Update Calculation: {name}' => 'Обновить расчет: {name}',
    'Update Color: {name}' => 'Обновить цвет: {name}',
    'Update Customer: {name}' => 'Обновить данные клиента: {name}',
    'Update Employee: {name}' => 'Обновить сотрудника: {name}',
    'Update Material: {name}' => 'Обновить материал: {name}',
    'Update Order: {name}' => 'Обновить данные заказа: {name}',
    'Update Price List: {name}' => 'Обновить данные записи в прайс-листе: {name}',
    'User ID' => 'Пользователь',
    'Employee FullName' => 'ФИО сотрудника',
    'Customer FullName' => 'ФИО клиента',
    'FullPrice' => 'Стоимость материала',
    '(empty)' => '(не задано)',
    'Full Price' => 'Полная стоимость рекламного изделия:'
];
